name: Add release assets
run-name: Add release assets for ${{ github.event.release.tag_name }}

on:
  release:
    types:
    - released

jobs:
  Add_assets:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Add assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.event.release.tag_name }} helper_tools/install-*

    - name: Add checksum
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir dist
        cd dist
        gh release download ${{ github.event.release.tag_name }}
        sha256sum -b * >SHA2-256SUM
        gh release upload ${{ github.event.release.tag_name }} SHA2-256SUM
