name: Build and Test clip_share_server
run-name: building and testing clip_share_server
on:
  push:
    branches:
      - master
      - github_workflow
jobs:
  Build-and-Test:
    runs-on:  ubuntu-20.04
    env:
      TERM: xterm-256color
      DISPLAY: :0
    steps:
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make xvfb openssl xclip python2.7 xxd diffutils coreutils netcat libc6-dev libx11-dev libxmu-dev libpng-dev libssl-dev
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build and Test
        run: |
          echo "Building..."
          make
          echo "Build completed"
          echo "Testing..."
          sudo Xvfb :0 -screen 0 1280x720x30 > /dev/null 2>&1 &
          make test
          echo "Passed test"
