name: Build and Test
run-name: Build and Test on ${{ github.sha }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build-and-Test-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
        fetch-depth: 0
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
    - name: Build
      run: docker build -t clipshare:ubuntu -f docker/Dockerfile.ubuntu .
    - name: Test
      run: docker run clipshare:ubuntu

  Build-and-Test-on-Fedora:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
        fetch-depth: 0
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
    - name: Build
      run: docker build -t clipshare:fedora -f docker/Dockerfile.fedora .
    - name: Test
      run: docker run clipshare:fedora

  Build-and-Test-on-Arch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
        fetch-depth: 0
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
    - name: Build
      run: docker build -t clipshare:arch -f docker/Dockerfile.arch .
    - name: Test
      run: docker run clipshare:arch

  Build-and-Test-on-Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-openssl mingw-w64-x86_64-libpng mingw-w64-x86_64-libunistring mingw-w64-x86_64-diffutils openbsd-netcat mingw-w64-x86_64-python sed
    - name: Setup make
      run: |
        ln -s /mingw64/bin/mingw32-make.exe /mingw64/bin/make.exe
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
        fetch-depth: 0
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
    - name: Build
      run: |
        make
        make web
    - name: Test
      run: make test
